apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-service.fullname" . }}-config
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
data:
  NODE_ENV:   {{ .Values.env.NODE_ENV | quote }}
  PORT:       {{ .Values.env.PORT | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
