apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.fullname" . }}-config
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
data:
  GIN_MODE:   {{ .Values.env.GIN_MODE | quote }}
  PORT:       {{ .Values.env.PORT | quote }}
  DB_HOST:    {{ .Values.env.DB_HOST | quote }}
  DB_PORT:    {{ .Values.env.DB_PORT | quote }}
  DB_NAME:    {{ .Values.env.DB_NAME | quote }}
  DB_USER:    {{ .Values.env.DB_USER | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
